Feature / Defi Positions
AmbireTech/ambire-common pull request #1062
Opened 2024-10-31 15:11 UTC by sonytooo

2024-11-04 10:43 UTC, PetromirDev requested changes

2024-11-04 10:43 UTC, PetromirDev commented on src/libs/defiPositions/types.ts
> +  network: string
rename to networkId

2024-11-04 11:05 UTC, PetromirDev requested changes

2024-11-04 12:40 UTC, PetromirDev requested changes

2024-11-04 12:40 UTC, PetromirDev commented on src/libs/defiPositions/types.ts
> +  network: string
Wait, it's actually the name of the network. Why is it not the networkId?
![image](https://github.com/user-attachments/assets/b74fd024-71d9-4f08-b0e4-a68e90909905)

2024-11-05 09:17 UTC, sonytooo commented on src/libs/defiPositions/types.ts
> +  network: string
only aave positions have positionInUsd

2024-11-07 09:06 UTC, PetromirDev approved these changes

2024-11-08 14:59 UTC, merged