WIP: Refactor/ Estimation error handling
AmbireTech/ambire-common pull request #1092
Opened 2024-11-13 15:50 UTC by PetromirDev

2024-11-18 09:21 UTC, borislav-itskov requested changes

2024-11-18 09:21 UTC, borislav-itskov commented on src/libs/estimate/errors/helpers.ts
> +      return 'The transaction could not be sent due to insufficient funds for the transaction fee. Please add more fee tokens to your account and try again.'
And this is the SA version. I guess the above error message will appear only on broadcast?

![Screenshot from 2024-11-18 11-05-32](https://github.com/user-attachments/assets/9cdec13f-c845-4ec2-817c-4befbb554e31)

2024-11-18 09:21 UTC, borislav-itskov commented on src/libs/estimate/errors/estimateErrors.test.ts
> +        'Transaction cannot be sent because of an unknown error. Please try again or contact Ambire support for assistance.'
Here, we know it's a relayer error but we don't say it to the user. Let's go and do something like:
* The Ambire relayer is currently down OR
OR
* The Ambire server is currently experiencing technical difficulties

Of course, we keep "Please try again or contact Ambire support for assistance"

2024-11-18 09:55 UTC, PetromirDev commented on src/libs/estimate/errors/helpers.ts
> +      return 'The transaction could not be sent due to insufficient funds for the transaction fee. Please add more fee tokens to your account and try again.'
We agreed to keep the error as-is

2024-11-21 09:40 UTC, borislav-itskov approved these changes

2024-11-22 09:03 UTC, merged