Fix/ Pinned Tokens Not Passed to Portfolio lib on failed RPC
AmbireTech/ambire-common pull request #1130
Opened 2024-11-27 13:39 UTC by gergana95

Closes [3294](https://github.com/AmbireTech/ambire-app/issues/3294)

2024-12-02 09:04 UTC, PetromirDev commented on src/libs/banners/banners.ts
> -  )
With this change, users will see error banners on irrelevant networks

2025-01-13 12:19 UTC, gergana95 commented on src/libs/banners/banners.ts
> -  )
Updated and removed this.

2025-01-27 10:09 UTC, PetromirDev requested changes

2025-01-27 10:09 UTC, PetromirDev commented on src/controllers/portfolio/portfolio.ts
> +      }
This check is incorrect. `networksWithAssetsByAccount` was never an array- its values were. We should check every key's value or introduce a `@v2` storage key and no longer use the old one.

2025-01-27 10:09 UTC, PetromirDev commented on src/controllers/portfolio/portfolio.ts
> +      }
![image](https://github.com/user-attachments/assets/9e7e7147-72d6-4603-a2c5-99f919a6ae3c)

2025-02-03 13:47 UTC, PetromirDev approved these changes

2025-02-04 12:37 UTC, merged