WIP: Feature / Swap & Bridge API error handling and messaging
AmbireTech/ambire-common pull request #1157
Opened 2024-12-06 14:30 UTC by superKalo

2025-01-31 10:19 UTC, PetromirDev requested changes

2025-01-31 10:19 UTC, PetromirDev commented on src/services/socket/api.ts
> +      const error = `${errorPrefix} Upstream error: <${message}>, status: <${status}>`
Perhaps we can hide Upstream error: `no message` and status: `unknown`.

2025-01-31 10:19 UTC, PetromirDev commented on src/services/socket/api.ts
> +          })
I'm pretty sure that we have to fallback to an object because we are spreading ...

2025-01-31 10:19 UTC, PetromirDev commented on src/services/socket/api.ts
> +      errorPrefix: 'Unable to start the route.'
Could we improve this message?

2025-01-31 10:19 UTC, PetromirDev commented on src/services/socket/api.ts
> +        })
again, this could cause an error

2025-01-31 10:38 UTC, PetromirDev requested changes

2025-01-31 10:38 UTC, PetromirDev commented on src/libs/swapAndBridge/swapAndBridgeErrorHumanizer.ts
> +  return new Error(errorMessage)
Trim the message if it exceeds x characters

2025-01-31 16:13 UTC, superKalo commented on src/services/socket/api.ts
> +          })
This conditional spread is safe, it handles both cases (presence and absence of `fromAsset`) gracefully without causing errors 🙄 

I asked an AI friend to write a test, that we can run in the browser console, that proofs this:

```
// Define a function that uses the conditional spread operator
function normalizeUserTx(userTx) {
  return {
    ...userTx,
    ...('fromAsset' in userTx && {
      fromAsset: `normalized_${userTx.fromAsset}`
    }),
    toAsset: `normalized_${userTx.toAsset}`
  };
}

// Test cases
const testCases = [
  { input: { toAsset: 'asset1' }, expected: { toAsset: 'normalized_asset1' } },
  { input: { fromAsset: 'asset2', toAsset: 'asset3' }, expected: { fromAsset: 'normalized_asset2', toAsset: 'normalized_asset3' } }
];

// Execute test cases
testCases.forEach(({ input, expected }, index) => {
  const result = normalizeUserTx(input);
  console.log(`Test case ${index + 1}:`, JSON.stringify(result) === JSON.stringify(expected) ? 'Passed' : 'Failed');
});
```

Tests passed ✅

2025-01-31 16:14 UTC, superKalo commented on src/services/socket/api.ts
> +        })
Same as https://github.com/AmbireTech/ambire-common/pull/1157#discussion_r1937557694

2025-01-31 16:32 UTC, superKalo commented on src/services/socket/api.ts
> +      errorPrefix: 'Unable to start the route.'
The title of the card is "Pending route", the call to action is "Proceed", that's why "Unable to start the route" makes sense to me. I can sync up for all these messages at batch with Stefan down the road, closing this one now so as not to block the PR.

2025-01-31 20:21 UTC, superKalo commented on src/services/socket/api.ts
> +      const error = `${errorPrefix} Upstream error: <${message}>, status: <${status}>`
I changed it to displaying the status only if one exists in https://github.com/AmbireTech/ambire-common/pull/1157/commits/f251912586546a977c52002fa8451efea15db7a2, but left the message as is, since I haven't yet had a situation with no message (and it might be actually useful if we see no message from the upstream provider while getting bug reports).

2025-01-31 20:33 UTC, superKalo commented on src/libs/swapAndBridge/swapAndBridgeErrorHumanizer.ts
> +  return new Error(errorMessage)
That's an excellent idea, thanks! Protection against crazy long error messages added in https://github.com/AmbireTech/ambire-common/pull/1157/commits/b573fc69ec34383e1fd6c1bb82fabecf9b5e80bc

2025-02-03 15:49 UTC, sonytooo approved these changes

2025-02-03 16:33 UTC, merged