Refactor / Portfolio Additional
AmbireTech/ambire-common pull request #754
Opened 2024-05-16 11:56 UTC by gergana95

Closes:
[1714](https://github.com/AmbireTech/ambire-app/issues/1714)
[2176](https://github.com/AmbireTech/ambire-app/issues/2176)

2024-05-16 12:27 UTC, Ivshti approved these changes

2024-05-20 12:22 UTC, PetromirDev requested changes

2024-05-20 12:22 UTC, PetromirDev commented on src/libs/portfolio/helpers.ts
> +  t.reduce((cur: any, token: any) => {
Replace any

2024-05-20 12:22 UTC, PetromirDev commented on src/libs/portfolio/helpers.ts
> +    return localCur
const localCur = cur still points to the same reference

2024-05-20 12:22 UTC, PetromirDev commented on src/libs/portfolio/helpers.ts
> +  availableGasTankAssets: any,
replace any

2024-05-23 12:13 UTC, PetromirDev approved these changes

2024-05-23 15:18 UTC, merged