Fix: none state-override rpcs
AmbireTech/ambire-common pull request #824
Opened 2024-06-18 13:37 UTC by borislav-itskov

Fix: if state override is not supported by the network, do not perform simulation; also, get the balances in a way that doesn't break the portfolio

2024-06-18 15:23 UTC, Ivshti requested changes
simulations can work without state override too, using ``Detect` mode

2024-07-02 13:37 UTC, borislav-itskov commented
> simulations can work without state override too, using ``Detect` mode

Fixed

2024-07-03 07:16 UTC, Ivshti commented
Discussed with Bobi that this is a compromise solution, because in the case where Detect is used and we use normal mode, the internal call will not execute, but it will not fail either (because it will be to an EOA without code)

2024-07-11 07:51 UTC, Ivshti approved these changes

2024-07-11 07:53 UTC, merged