Feature / Claim Wallet Rewards
AmbireTech/ambire-common pull request #850
Opened 2024-07-03 15:21 UTC by gergana95

Create sign account op from mainController to claim wallet rewards.

2024-07-04 08:54 UTC, Ivshti requested changes
I don't think mainCtrl  should get even more cluttered than it is and gain functionalities like this - let's think of a better solution

2024-07-04 10:02 UTC, PetromirDev requested changes
Fix tests

2024-07-04 10:02 UTC, PetromirDev commented on src/controllers/main/main.ts
> +    claimableRewardsData: any,
replace any

2024-07-04 10:02 UTC, PetromirDev commented on src/libs/portfolio/interfaces.ts
> +  claimableRewardsData: any
just add it next to total. Also replace any

2024-07-04 10:02 UTC, PetromirDev commented on src/libs/transfer/userRequest.ts
> +}: { selectedAccount: string, selectedToken: TokenResult, claimableRewardsData: any }): SignUserRequest | null {
replace any

2024-07-04 10:02 UTC, PetromirDev commented on src/libs/transfer/userRequest.ts
> +const WALLET_STAKING_ADDR = '0x47Cd7E91C3CBaAF266369fe8518345fc4FC12935'
Can we add these constants to some common file?

2024-07-08 09:26 UTC, PetromirDev requested changes

2024-07-08 09:26 UTC, PetromirDev commented on src/libs/transfer/userRequest.ts
> +import { Call, SignUserRequest } from 'interfaces/userRequest'
fix import

2024-07-08 12:10 UTC, merged