Add debug tracecall for nfts
AmbireTech/ambire-common pull request #913
Opened 2024-07-30 08:48 UTC by JIOjosBG

Adds debug_traceCall discovery for nft transfers

2024-08-10 16:18 UTC, Ivshti requested changes

2024-08-10 16:18 UTC, Ivshti commented on src/libs/tracer/debugTraceCall.ts
> +                type:"ERC-20",
we mix quote styles here, i would probably do `erc: 20` instead of `type: "ERC-20"` though. because all types would be ERCs

2024-08-10 16:18 UTC, Ivshti commented on src/libs/tracer/debugTraceCall.ts
> +  const [nftsWithErr] = await deploylessNfts.call(
we should call these two in parallel, not sequentially

2024-08-12 10:26 UTC, jordan-enev commented on src/controllers/portfolio/portfolio.ts
> +    if (!nftsData || !nftsData?.length) return false
`!nftsData?.length` should be sufficient

2024-08-12 10:37 UTC, jordan-enev commented on src/libs/tracer/debugTraceCall.ts
> +    ([k, v]) => [k, Array.from(v).map((i) => BigInt(i))]
address, id, instead of k, v

2024-08-12 10:42 UTC, jordan-enev commented on src/controllers/main/main.ts
> +    const { tokens, nfts } = await debugTraceCall(
we don't have any tests for `debugTraceCall` lib nor for the`main->traceCall`, would be great if we write tests for the discovery mechanism

2024-08-12 15:21 UTC, Ivshti approved these changes

2024-08-20 06:38 UTC, borislav-itskov requested changes

2024-08-20 06:38 UTC, borislav-itskov commented on src/libs/tracer/debugTraceCall.ts
> +      })
The return statement in `catch` is the old one. Maybe we should make it `return []` and check right after the promise if results are empty:
```
if (!results.length) return {tokens: [], nfts: []}
```

2024-08-22 12:24 UTC, borislav-itskov approved these changes

2024-08-22 13:34 UTC, jordan-enev approved these changes

2024-08-22 13:35 UTC, merged