Fix / hintsFromExternalAPI does not include deployless tokens
AmbireTech/ambire-common pull request #975
Opened 2024-08-28 15:07 UTC by gergana95

BUG: Currently we don't set in previousHints tokens with balance which is found from deployless.
This results in 2 issues:
1. On custom networks we wont be able to update periodically tokens with balance, without passing the learnedTokens to portfolio.
2. Tokens which are not returned from Velcro are not stored in previousHints. Resulting in this [bug](https://github.com/AmbireTech/ambire-app/issues/2747) - tokens like debt tokens will be showed only when learnedTokens are passed and on every reset of the extension they are removed, but on every force refresh they show up again.
3. We populate the timestamp to these tokens (found from learned with balance) when they are last seen non zero, hence those will be removed first from the learnedTokens on cleanup

2024-08-29 07:53 UTC, Ivshti requested changes
I think hintsFromExternalAPI should not be re-assigned, instead there should be a new constant allHints that is also the one being returned, and everyone using the portfolio lib output should use the allHints output.

Otherwise we introduce a naming issue right here, because everyone using hintsFromExternalAPI will actually be using an aggregate of all hints

Also, didn't we purposefully not store anything that is being returned by velcro? What happens with this decision? BEcause not having this means that we'll litter the storage quickly and have to remove tokens when we reach the limit

2024-08-29 11:08 UTC, gergana95 commented
@Ivshti 
Currently the structure in this PR is wrong and returns all hints (including preferences, pinned and etc.), the idea is to return hints from additionalHints with balance only, in order to store them in previousHints - from velcro and from deployless, so I will update it, good catch.
Do we need to return allHints structure and where would we use it? The lib returns tokens which is all hints as tokens with prices. It seems we will duplicate it this way, but maybe i am missing the point.

Regarding the velcro tokens caching, currently we ARE storing them in previousHints - fromExternalAPI structure. We discussed we will store them there while implementing this [issue](https://github.com/AmbireTech/ambire-app/issues/2109). This way we have a fallback if velcro is not available.

2024-09-02 11:40 UTC, PetromirDev requested changes
Please write a unit test for this logic.

2024-09-02 11:40 UTC, PetromirDev commented on src/controllers/portfolio/portfolio.ts
> +        !address === ZeroAddress
!address is a boolean. `!address === ZeroAddress` compares boolean and string

2024-09-02 11:40 UTC, PetromirDev commented on src/controllers/portfolio/portfolio.ts
> +        (a, b) => Number(b[1]) - Number(a[1])
Please add a comment because this `.sort` is hard to read

2024-09-02 11:40 UTC, PetromirDev commented on src/controllers/portfolio/portfolio.ts
> +    if (!this.#toBeLearnedTokens) this.#toBeLearnedTokens = {}
is this even possible?

2024-09-02 11:40 UTC, PetromirDev commented on src/controllers/portfolio/portfolio.ts
> +    if (!tokenAddresses) return false
`![] === true`. The correct check is `!tokenAddresses.length`

2024-09-02 11:40 UTC, PetromirDev commented on src/controllers/portfolio/portfolio.ts
> +    let networkToBeLearnedTokens = this.#toBeLearnedTokens[networkId] || []
|| [] isn't needed because of:
```
if (!this.#toBeLearnedTokens[networkId]) this.#toBeLearnedTokens[networkId] = []
```

2024-09-02 11:40 UTC, PetromirDev commented on src/controllers/portfolio/portfolio.ts
> +    this.#toBeLearnedTokens[networkId] = networkToBeLearnedTokens
Imo this logic is mostly unnecessary. I don't see a problem in adding all passed `tokenAddresses` to `toBeLearnedTokens`. After all, hints are deduped in portfolio lib and learnTokens doesn't allow duplicates.

2024-09-02 11:40 UTC, PetromirDev commented on src/libs/portfolio/helpers.ts
> +      const isTokenInToBeLearnedTokens = tobeLearnedTokens.includes(lowercaseAddress)
I don't think this check is ok. addresses in `toBeLearnedTokens` are checksummed and `lowercaseAddress` is lowercase

2024-09-02 11:40 UTC, PetromirDev commented on src/libs/portfolio/helpers.ts
> +        hasBalance
This condition is only true the first time based on the logic in the controller. We should update the timestamp every time the portfolio is updated and the token has balance.

2024-09-04 02:36 UTC, closed without merging